#ifndef MUDENGINEWORKER_H
#define MUDENGINEWORKER_H

#include <QObject>
#include <QString>

/**
 * @brief The MudEngineWorker class runs in a separate thread and handles
 * direct communication with the MUD (via ttcoreex) and script execution.
 *
 * It receives commands from the ProfileManager (originating from user input
 * or scripts) and emits signals back to the ProfileManager with text received
 * from the MUD or script output.
 *
 * Porting Notes:
 * - This class encapsulates the logic that was running in ClientThread in the MFC version.
 * - All ttcoreex API calls (InitState, CompileInput, ReadMud, ReloadScriptEngine, etc.)
 *   will eventually be called from within this class's methods.
 * - It runs in a QThread managed by ProfileManager to prevent blocking the UI.
 * - Communication with ProfileManager is done via signals and slots.
 */
class MudEngineWorker : public QObject
{
    Q_OBJECT
public:
    explicit MudEngineWorker(QObject *parent = nullptr);
    ~MudEngineWorker();

    // Method to initialize the worker with necessary data after moving to thread
    // For example, paths to script files, profile name for ttcoreex initialization.
    // This would be invoked via QMetaObject::invokeMethod from ProfileManager.
    // Q_INVOKABLE void initialize(/* Profile specific data */);


public slots:
    /**
     * @brief Processes a command string.
     * This could be user input or a command from a script/trigger.
     * For now, it will just echo the command back.
     * Later, it will call ttcoreex functions like CompileInput().
     */
    void processCommand(const QString& command);

    /**
     * @brief Slot to trigger reloading of scripts.
     * Corresponds to CSmcDoc::OnScriptingReload and the bReloadScripts flag.
     * Will eventually call ttcoreex's ReloadScriptEngine().
     */
    // Q_INVOKABLE void reloadScripts(const QString& allScriptsText, const QByteArray& scriptEngineGuid);

    /**
     * @brief Slot to initialize the ttcoreex engine.
     * Corresponds to InitState() and would be called after profile loading.
     */
    // Q_INVOKABLE void initializeEngine(/* necessary params like main window handle for callbacks */);

    /**
     * @brief Main processing loop, if ttcoreex requires one (like ReadMud()).
     * This could be started by a timer or run continuously after initialization.
     */
    // void doWork(); // This might be a loop started by a timer or run in its own method

    /**
     * @brief Initializes the ttcoreex engine.
     * Called via QMetaObject::invokeMethod from ProfileManager after thread starts.
     * @param parentWindowId The window ID (WId) of the main window, if needed by ttcoreex.
     */
    Q_INVOKABLE void initializeEngine(WId parentWindowId);

    /**
     * @brief Starts the main processing loop (e.g., for ReadMud).
     * Called via QMetaObject::invokeMethod after engine initialization.
     */
    Q_INVOKABLE void startProcessing();

    /**
     * @brief Slot to trigger reloading of scripts.
     * @param scriptText The combined text of all scripts to load.
     * @param profileName The current profile name, possibly used by ttcoreex.
     */
    Q_INVOKABLE void reloadAllScripts(const QString& scriptText, const QString& profileName);

    /**
     * @brief Slot to break current script execution.
     */
    Q_INVOKABLE void breakCurrentScript();

    /**
     * @brief Slot to launch the script debugger.
     */
    Q_INVOKABLE void launchScriptDebugger();


signals:
    /**
     * @brief Emitted when text is received from the MUD or generated by the script engine.
     * @param wndCode The target window code (0 for main, 1-N for auxiliary).
     * @param text The text string (may contain ANSI codes).
     */
    void textReceived(int wndCode, const QString& text);

    /**
     * @brief Emitted when the MUD engine/script requests the display to be cleared.
     * @param wndCode The target window code.
     */
    void clearDisplayRequested(int wndCode);

    /**
     * @brief Signal that the worker has finished its task (e.g. on quit).
     */
    void finished();

    /**
     * @brief Signal to report an error.
     */
    void errorOccurred(const QString& errorString);


private:
    bool m_quitSignaled; // Flag to indicate the worker should stop processing
    // Add members for ttcoreex state, script engine interface, etc. later.

    // Callback functions that can be registered with ttcoreex (static or helper class)
    // static void ttCoreOutputCallback(const wchar_t* text, int wndCode);
    // static void ttCoreClearCallback(int wndCode);
    static MudEngineWorker* s_instance; // For static callbacks to reach the instance

    // Static callback functions for ttcoreex
    static void __stdcall ttCoreOutputCallbackProxy(const wchar_t* text, int wndCode);
    static void __stdcall ttCoreClearCallbackProxy(int wndCode);
    // Add other callbacks here if ttcoreex uses them (e.g., for connection status)

private:
    // Helper methods for the instance to handle proxied calls
    void handleTtCoreOutput(const wchar_t* text, int wndCode);
    void handleTtCoreClear(int wndCode);
};

#endif // MUDENGINEWORKER_H
